version: '3.8'
services:
  nginx:
    build:
      context: ./server_1
    container_name: server-nginx
    volumes:
      - ./server_1/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - '80:80'
    links:
      - web
  web:
    build:
      context: ./server_2
    container_name: server-php
    volumes:
      - ./server_2/web:/usr/share/nginx/html
    ports:
      - '81:80'
